### ISSUE TITLE
Destination Address Phone Number is required for DHL Express and UPS International Orders

### ISSUE THREAD

**Issue by bborman22** [Automattic/woocommerce-services#2276]
We had been getting a few reports of merchants unable to purchase DHL Express labels and receiving a generic error message. Upon digging deeper it appears that the Destination Address Phone number is a required field for these label purchases. With some testing I was able to confirm that this error is triggered when purchasing an international label through DHL Express or UPS, but is not triggered on USPS international labels.

Since the majority of the services require this field, I was thinking it would be best to require the field for all international orders. I was going to call out three things that would be needed to address this issue:

1. Update the documentation to mention that Destination Address Phone Number is required for International orders as this would require the merchant to update their site settings.
2. Display a more useful error message to the merchant, though this may need to come from the Connect server.
3. Make the field required for international orders similar to what was done for the From Address.

For 3 I was thinking making a [similar check to destination as origin](https://github.com/Automattic/woocommerce-services/blob/be6d1fcb0396143ba0dfc5c7546ad82035d611f6/client/extensions/woocommerce/woocommerce-services/state/shipping-label/selectors.js#L487-L490) if a customs form is required?

**Steps to Reproduce**
1. Place an international order that would be eligible for DHL Express.
2. Go to create a shipping label for the order.
3. Remove the Destination Address phone number (if one was provided).
4. Attempt to purchase the shipping label.
5. Get generic error message about a problem purchasing the shipping label.

![Screen Shot 2020-12-04 at 2 17 54 PM](https://user-images.githubusercontent.com/68524302/101205405-94a8e880-363b-11eb-9a54-36e1457aa5bc.png)

**Comment by aleftick** [comment]
I emailed DHL to confirm what they require. It could be that the recipient email is sufficient and if so that might make it easier for merchants to comply (since all orders tend to have that info).

**Comment by lindamork** [comment]
#3554060-zd  (opened as a followup to Senff's chat above) I’ve confirmed that a phone number was added to the Destination address for DHL, but in this case it’s a 13 digit number for China. Any chance it’s not liking 13 digits over the regular 10 and that’s why it’s refunding @bborman22 ? Thanks! 

<img width="736" alt="Markup 2020-12-07 at 14 38 09" src="https://user-images.githubusercontent.com/16885584/101536297-a990bf00-394e-11eb-966b-a4a97fb88474.png">

**Comment by bborman22** [comment]
@lindamork I checked in with EasyPost and this particular shipment was prevented because of a limitation they introduced then rolled back. This user should now be able to purchase this label with that limitation rolled back.

For broader reference the message from EasyPost was:

> On December 3rd, EasyPost made a change to our DHL Express integration to make ECCN mandatory to the three counties. On December 7th we rolled back the change as this won't be mandatory with DHL until sometime in January. I am unsure if EasyPost will require the ECCN field or if we will leave it up to DHL to enforce the ECCN value.

> An ECCN value is required for shipments going to China, Russia, and Venezuela.

Since these reasons for purchase rejections could vary, we have created an issue on the Connect server to log and hopefully pass along these error messages to the user.

**Comment by senff** [comment]
The customer who reached out to us in #26172868-HC (and Linda's follow-up #3554060-zd) reported that they were able to print the label now, so that particular one is solved. Thanks!

**Comment by yukikatayama** [comment]
Noting that similar issue is happening with customer in 29053734-hc.

**Comment by bloukingfisher** [comment]
This issue is still present for DHL international shipments missing a phone number. The error message: "There was a problem purchasing your shipping label. Please try again in a moment." is misleading and not helpful.
Even when enabling the debug/log setting, the log doesn't show the problem either. It is virtually impossible for a user to figure out the problem without at least a better error message (until you can figure out the requirement/non-requirement flow of a phone number).
I had a support ticket open for this, request 4035990.

**Comment by c-shultz** [comment]
>The error message: "There was a problem purchasing your shipping label. Please try again in a moment." is misleading and not helpful.

Agreed. I'm bumping this to critical since it sounds like a major potential blocker for using this feature.

**Comment by isramos** [comment]
This is a major flaw. I'm glad I came across this write-up. I put the phone number and it worked!  One hour of my evening was wasted on this issue :( 
(FYI: another flaw is that if you have a PO box as the sender address, it also fails. You must have a physical street address as the sender. Again, lacking the proper error message)

**Comment by RiaanKnoetze** [comment]
Flagging this issue that popped up for [Checkout Field Editor](https://woocommerce.com/products/woocommerce-checkout-field-editor/?aff=10486&cid=1131038): 

191-gh-woocommerce/woocommerce-checkout-field-editor

I'm unsure if this is already the case, but if the customer is _only_ using [WooCommerce Shipping & Tax](https://woocommerce.com/products/shipping/?aff=10486&cid=1131038) for tax calculation (and not label printing), I don't think an extra phone field is necessary on the checkout page.
