### ISSUE TITLE
Shipping Label Reports display HTML

### ISSUE THREAD

**Issue by thisissandip** [Automattic/woocommerce-services#2658]
The issues show up when a merchant views their Shipping labels under WooComemrce > Reports > Shipping Labels.

Shipping Labels Report: WooCommerce Reports > Shipping Labels tab:

![https://user-images.githubusercontent.com/85893744/248057835-249ac97f-6107-4f0c-a563-560933e34044.png](https://user-images.githubusercontent.com/85893744/248057835-249ac97f-6107-4f0c-a563-560933e34044.png)

Initially, this was submitted in WooCommerce Core repo: https://github.com/woocommerce/woocommerce/issues/38900

**Comment by harriswong** [comment]
Make sure QIT and semgrep pass when we fix this.

**Comment by muhammedsafiulazam** [comment]
Vendor's reports are completely broken as well.
Console says "woocommerce_admin" is not defined in js.

**Comment by muhammedsafiulazam** [comment]
Any idea when you are going to fix this? This is really important for vendors in Product Vendors.

**Comment by muhammedsafiulazam** [comment]
I have just installed your latest update. 
Login as a vendor and you will see that reports are still broken.

**Comment by tvolpert** [comment]
one of the users affected by the original issue (that was closed and split off into this one) came back to request an update. I let them know we would contact them if/when a fix is available.

6643507-zen

**Comment by muhammedsafiulazam** [comment]
Just installed 2.2.0 and reports ( it's not only shipping ) are still broken.
Can you guys please make it a priority? Without reports it's pretty much useless.
Thank you.

**Comment by harriswong** [comment]
Hi, this issue will be fixed in 2.3.4.

**Comment by muhammedsafiulazam** [comment]
Last update has fixed the issue but has created a new bug.  Now we can't change vendor logo in Product Vendors.

**Comment by harriswong** [comment]
HI @muhammedsafiulazam , can you create a separate issue please? In the new issue, please describe the steps to reproduce and we will go from there. Thank you.
